### ISSUE TITLE
Find new font & font size

### ISSUE THREAD

**Issue by ngoiyaeric** [QueueLab/Landing#6]
open to suggestions

**Comment by rosaleensiroosi** [comment]
i tried testing out font name albert sans. here is what the landing page would look like with this font.
<img width="1710" alt="image" src="https://github.com/QueueLab/Landing/assets/171291607/865b524f-5abc-40c5-85c2-4939663476dc">
please let me know what you think; if you like it, i can implement and create a pull request!

**Comment by ngoiyaeric** [comment]
I like it, let's merge it for now.
